/**
 * Managed profile decoration — 让托管 Chrome 一眼可辨。
 *
 * 移植自 OpenClaw `extensions/browser/src/browser/chrome.profile-decoration.ts`（MIT），
 * 做法：写 `<userDataDir>/Local State` 与 `<userDataDir>/Default/Preferences`。
 *
 * 两个目的：
 *  1. **标识**：profile 命名 + 橙色染色 → 用户不会把它当成自己想打开的浏览器误操作。
 *  2. **清异常退出标记**：托管模式 show/hide 切换会 kill Chrome，Chrome 会记为"异常退出"，
 *     下次启动弹「恢复页面？」气泡。写 `exit_type=Normal` 可避免。
 *
 * 全部 **best-effort**：Chrome 的 pref 键各版本不一，失败不许影响浏览器启动。
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

export const MANAGED_PROFILE_NAME = "Pi 自动化";
export const MANAGED_PROFILE_COLOR = "#FF6A00"; // 橙色，与日常 Chrome 区分

function readJson(filePath: string): Record<string, unknown> {
  try {
    const parsed = JSON.parse(readFileSync(filePath, "utf-8")) as unknown;
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

function writeJson(filePath: string, data: unknown): void {
  mkdirSync(dirname(filePath), { recursive: true });
  writeFileSync(filePath, JSON.stringify(data), "utf-8");
}

function setDeep(obj: Record<string, unknown>, keys: string[], value: unknown): void {
  let node: Record<string, unknown> = obj;
  for (const key of keys.slice(0, -1)) {
    const next = node[key];
    if (typeof next !== "object" || next === null || Array.isArray(next)) node[key] = {};
    node = node[key] as Record<string, unknown>;
  }
  node[keys[keys.length - 1] ?? ""] = value;
}

/** "#RRGGBB" → Chrome 用的有符号 32 位 SkColor 整数。 */
function hexToSignedArgb(hex: string): number | null {
  const cleaned = hex.trim().replace(/^#/, "");
  if (!/^[0-9a-fA-F]{6}$/.test(cleaned)) return null;
  const rgb = Number.parseInt(cleaned, 16);
  const unsigned = (0xff << 24) | rgb;
  return unsigned > 0x7fffffff ? unsigned - 0x1_0000_0000 : unsigned;
}

/** 给托管 profile 设置名称与颜色（best-effort、幂等）。 */
export function decorateManagedProfile(
  userDataDir: string,
  name: string = MANAGED_PROFILE_NAME,
  colorHex: string = MANAGED_PROFILE_COLOR,
): void {
  const color = colorHex.toUpperCase();
  const colorInt = hexToSignedArgb(color);

  const localStatePath = join(userDataDir, "Local State");
  const localState = readJson(localStatePath);
  setDeep(localState, ["profile", "info_cache", "Default", "name"], name);
  setDeep(localState, ["profile", "info_cache", "Default", "shortcut_name"], name);
  setDeep(localState, ["profile", "info_cache", "Default", "user_name"], name);
  setDeep(localState, ["profile", "info_cache", "Default", "profile_color"], color);
  setDeep(localState, ["profile", "info_cache", "Default", "user_color"], color);
  if (colorInt !== null) {
    // 这几个是 Chrome 真正用于 profile / 头像染色的字段。
    setDeep(localState, ["profile", "info_cache", "Default", "profile_color_seed"], colorInt);
    setDeep(localState, ["profile", "info_cache", "Default", "profile_highlight_color"], colorInt);
    setDeep(localState, ["profile", "info_cache", "Default", "default_avatar_fill_color"], colorInt);
    setDeep(localState, ["profile", "info_cache", "Default", "default_avatar_stroke_color"], colorInt);
  }
  writeJson(localStatePath, localState);

  const preferencesPath = join(userDataDir, "Default", "Preferences");
  const prefs = readJson(preferencesPath);
  setDeep(prefs, ["profile", "name"], name);
  setDeep(prefs, ["profile", "profile_color"], color);
  setDeep(prefs, ["profile", "user_color"], color);
  if (colorInt !== null) {
    setDeep(prefs, ["autogenerated", "theme", "color"], colorInt);
    setDeep(prefs, ["browser", "theme", "user_color2"], colorInt);
  }
  writeJson(preferencesPath, prefs);
}

/**
 * 清掉"异常退出"标记，避免重启后弹「恢复页面？」气泡、并进入崩溃恢复模式。
 * （崩溃恢复模式会让新启动的浏览器卡在「恢复页面」状态、页面不可用，注入的页面脚本
 *   也就无从生效——表现为工具取不到页面。show/hide 切换会 kill Chrome，故必须清。）
 *
 * ⚠️ 必须同时清 `Preferences` 与 `Local State` 两处：
 *  - `Default/Preferences` 的 `exit_type` 只是 per-profile 标记；
 *  - Chrome 真正决定是否进崩溃恢复模式、是否弹气泡的是 **`Local State`**
 *    （`profile.info_cache.Default.exit_type` 以及全局 `browser.exit_type`）。
 *  之前只改 Preferences，导致 dev 重启强杀旧实例后 `Local State` 仍是 Crashed，
 *  新 Chrome 一启动就进恢复模式——必须点「恢复页面」才通。
 */
export function ensureProfileCleanExit(userDataDir: string): void {
  // 1) per-profile：Default/Preferences
  const preferencesPath = join(userDataDir, "Default", "Preferences");
  const prefs = readJson(preferencesPath);
  setDeep(prefs, ["exit_type"], "Normal");
  setDeep(prefs, ["exited_cleanly"], true);
  writeJson(preferencesPath, prefs);

  // 2) global：Local State（崩溃恢复模式的真正判据）
  const localStatePath = join(userDataDir, "Local State");
  const ls = readJson(localStatePath);
  setDeep(ls, ["profile", "info_cache", "Default", "exit_type"], "Normal");
  setDeep(ls, ["profile", "info_cache", "Default", "exited_cleanly"], true);
  setDeep(ls, ["browser", "exit_type"], "Normal");
  writeJson(localStatePath, ls);
}
